# 1.2 Basic Grammer

## 1.2.1 Variables and Basic Operations

In [1]:
x = 3
y = 1.2
z = "Hi!"

"Hi!"

In [2]:
typeof(x)

Int64

In [3]:
typeof(y)

Float64

In [4]:
typeof(z)

String

In [5]:
x + 1

4

### Unicode input https://docs.julialang.org/en/v1/manual/unicode-input/

In [6]:
# ギリシャ文字
μ = 0.0 #(\mu)
σ = 2.0 #(\sigma)
# 下付き
xᵢ = 0 #(x\_i)
# 上付き
σ² = σ^2 #(\sigma\^2)

4.0

## 1.2.2 Control Syntax

In [7]:
x = 1.0
y = 2.0
if x < y
    println(" x is less than y. ")
elseif x ==y
    println("x is equal to y. ")
else
    println("x is greater than y. ")
end

 x is less than y. 


In [8]:
x = -3
y = x < 0 ? "T" : "F" # Ternary operator
println(y)

T


In [9]:
a = 0
b = 0
true && (a = 1) # Short-Circuit Evaluation
true || (b = 1)
println("a = $(a), b = $(b)")

a = 1, b = 0


In [10]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


## 1.2.3 Function

In [11]:
myinv(x) = 1/x

myinv (generic function with 1 method)

In [12]:
myinv(3)

0.3333333333333333

In [13]:
function myinv(x)
    return 1/x    # returnは省略可能
end

myinv (generic function with 1 method)

In [14]:
function mymean(x, y)
    return (x + y) / 2
end

mymean (generic function with 1 method)

In [15]:
mymean(1.0, 2.0)

1.5

## 1.2.4 Array

In [16]:
a = [1, 2, 3] # 縦ベクトル（, ~カンマ~で区切る）

3-element Vector{Int64}:
 1
 2
 3

In [17]:
b = [1, 2, 3] # 横ベクトル（" "~スペースで区切る），1x3行列とみなされる

3-element Vector{Int64}:
 1
 2
 3

In [18]:
c = Array{Float64}(undef, 3) # 各要素がFloat64型の配列を，値を初期化せずにメモリ上に確保

3-element Vector{Float64}:
 2.3719286923e-314
 2.247177425e-314
 2.3709330433e-314

In [19]:
d = zeros(3) # zeros関数 ゼロを並べた配列

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [20]:
e = ones(3) # ones関数 1を並べた配列

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [21]:
f = rand(3) # rand関数 0~1までの一様にランダムな実数を生成

3-element Vector{Float64}:
 0.8580841476014234
 0.8477210080594701
 0.2655787984616036

In [22]:
g = randn(3) # randn関数 平均0，標準偏差1の正規分布から乱数を得る

3-element Vector{Float64}:
 0.3897673908800641
 0.22440543886835512
 1.465828852103693

In [23]:
A = [1 2 3 4; 
     5 6 7 8] # 2x4サイズの行列

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [24]:
B = ones(2, 4)

2×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [25]:
size(A) # size関数 行列のサイズを得る

(2, 4)

In [26]:
length(A) # lenngth関数 ベクトルや行列の要素の個数を得る

8

In [27]:
A[2, 1] # 2行, 1列目の要素を出力

5

In [28]:
A[2, :] # 2行目を配列として出力

4-element Vector{Int64}:
 5
 6
 7
 8

In [29]:
A[:, 1] # 1行目を配列として出力

2-element Vector{Int64}:
 1
 5

In [30]:
A[:, 1:3] # 1~3列目を部分行列として出力

2×3 Matrix{Int64}:
 1  2  3
 5  6  7

In [31]:
[2*i for i in 1:5] # ループを使って配列を生成

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [32]:
[i*j for i in 1:3, j in 1:4] # ループを2つ回して行列を生成

3×4 Matrix{Int64}:
 1  2  3   4
 2  4  6   8
 3  6  9  12

In [33]:
params = (1, 2, 3) #タプル（tuple）

(1, 2, 3)

In [34]:
f(a, b, c) = a + b + c
f(params...)

LoadError: cannot define function f; it already has a value

## 1.2.5 ブロードキャスト (broadcast)

In [35]:
a = [1, 2, 3] # 縦ベクトル
a + 1         # エラーが出る例

LoadError: MethodError: no method matching +(::Vector{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:313
  ...

In [36]:
a .+ 1  # Juliaではドット（.）を付けた.+演算子は要素毎の計算を行うことを意味する．

3-element Vector{Int64}:
 2
 3
 4

In [37]:
function add_one(x) # 与えられた変数に対して1を加える関数
    x + 1
end
add_one(1.0)

2.0

In [38]:
add_one.([1, 2, 3]) # 配列の各要素に関して計算するために，add_one関数にドットを付けて，add_one. とする．

3-element Vector{Int64}:
 2
 3
 4

## 1.2.4 無名関数（anonymous function）

In [39]:
x -> x + 1

#5 (generic function with 1 method)

In [40]:
map(x -> x + 1, [1, 2, 3]) # map関数

3-element Vector{Int64}:
 2
 3
 4

## 1.2.7 マクロ（macro）

In [41]:
function test(maxiter)
    a = []
    for i in 1:maxiter
        push!(a, randn())
    end
    sum(a)
end
@time test(100000)

  0.007379 seconds (201.39 k allocations: 4.962 MiB, 36.64% compilation time)


479.1043857040541